services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build: .
    container_name: fastapi-container
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:password@host.docker.internal:5432/mydatabase
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./app/secrets:/app/secrets
    command:
      - sh
      - -c
      - "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data:
