"""Change hours to INTEGER

Revision ID: 69a40cc3da48
Revises: 1f0bda2f9149
Create Date: 2025-02-22 17:19:27.283469

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "69a40cc3da48"
down_revision: Union[str, None] = "1f0bda2f9149"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
