"""Add bikename column to bicycles

Revision ID: a6770a1345a2
Revises: 265fd782179f
Create Date: 2025-02-25 06:59:42.842654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6770a1345a2'
down_revision: Union[str, None] = '265fd782179f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bicycles', sa.Column('bikename', sa.String(length=50), nullable=False))
    op.alter_column('reservations', 'bicycle_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservations', 'bicycle_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('bicycles', 'bikename')
    # ### end Alembic commands ###
