"""Change bicycle_id to BIGINT

Revision ID: ae98c020ae5f
Revises: 69a40cc3da48
Create Date: 2025-02-22 17:45:39.667907

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ae98c020ae5f"
down_revision: Union[str, None] = "69a40cc3da48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
